version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: monthly
    target-branch: v2
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    target-branch: v2
