name: test action
on:
  push:
    branches:
      - v2
  workflow_dispatch:

jobs:
  install:
    name: test action
    runs-on: ubuntu-latest
    steps:
      - uses: kayac/ecspresso@v0
        with:
          version: v1.5.0
      - run: |
          ecspresso version 2>&1 | fgrep -q v1.5.0
      - uses: kayac/ecspresso@v1
        with:
          version: v1.5.0
      - run: |
          ecspresso version 2>&1 | fgrep -q v1.5.0
      - uses: kayac/ecspresso@v1
        with:
          version: v1.6.0
      - run: |
          ecspresso version 2>&1 | fgrep -q v1.6.0
      - uses: kayac/ecspresso@v1
        with:
          version: latest
      - run: |
          ecspresso version 2>&1 | fgrep -q v1.7.
      - uses: kayac/ecspresso@v2
        with:
          version: latest
      - run: |
          ecspresso version 2>&1 | fgrep -q v2.
      - uses: kayac/ecspresso@v2
        with:
          version: v1.7.14
      - run: |
          ecspresso version 2>&1 | fgrep -q v1.7.14
