name: test action
on:
  push:
    branches:
      - v2
      - v2-action-testing
  workflow_dispatch:

jobs:
  install:
    strategy:
      matrix:
        action_version: ['v0', 'v1', 'v2', 'v2-action-testing']
        install_version: ['latest', 'v1.7.15', 'v2.1.0']

    name: test action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: "kayac/ecspresso@{{ matrix.action_version }}"
        with:
          version: "{{ matrix.install_version }}"
      - run: |
          ecspresso version
